# Generated by Django 5.0.6 on 2024-06-13 12:39

import django.db.models.deletion
import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Profile', '0001_initial'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=250)),
                ('about_genre', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_name', models.CharField(max_length=500)),
                ('release_date', models.DateField()),
                ('music_number', models.IntegerField()),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Music.genre')),
            ],
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('music_name', models.CharField(max_length=350)),
                ('release_date', models.DateField()),
                ('post_date', models.DateField()),
                ('cover_art', models.FileField(upload_to='media/images/cover_art')),
                ('music', models.FileField(upload_to='media/music')),
                ('lyrics', models.TextField(blank=True, null=True)),
                ('review', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(unique=True)),
                ('views', models.IntegerField()),
                ('album', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Music.album')),
                ('music_genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Music.genre')),
                ('tag', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Profile.profile')),
            ],
        ),
        migrations.CreateModel(
            name='IntermediateModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('music', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Music.music')),
            ],
        ),
        migrations.CreateModel(
            name='BandOfMusic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('position_in_band', models.CharField(blank=True, max_length=200, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('music', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Music.music')),
            ],
        ),
        migrations.CreateModel(
            name='Singer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('birth', models.DateField(blank=True, null=True)),
                ('death', models.DateField(blank=True, null=True)),
                ('about_singer', models.TextField(blank=True, null=True)),
                ('genre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Music.genre')),
            ],
        ),
        migrations.AddField(
            model_name='music',
            name='singer',
            field=models.ManyToManyField(through='Music.IntermediateModel', to='Music.singer'),
        ),
        migrations.AddField(
            model_name='intermediatemodel',
            name='singer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Music.singer'),
        ),
        migrations.AddField(
            model_name='album',
            name='singer',
            field=models.ManyToManyField(related_name='albums', to='Music.singer'),
        ),
        migrations.CreateModel(
            name='Vibe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.FileField(upload_to='media/images/vibes')),
                ('music', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Music.music')),
            ],
        ),
    ]
