# Generated by Django 5.0.6 on 2024-06-13 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0002_alter_intermediatemodel_singer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intermediatemodel',
            name='singer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Music.singer'),
        ),
    ]
