# Generated by Django 5.0.6 on 2024-06-13 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0003_alter_intermediatemodel_singer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intermediatemodel',
            name='music',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Music', to='Music.music'),
        ),
        migrations.AlterField(
            model_name='intermediatemodel',
            name='singer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Singers', to='Music.singer'),
        ),
    ]
