# Generated by Django 5.0.6 on 2024-06-13 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0004_alter_intermediatemodel_music_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='views',
            field=models.PositiveIntegerField(),
        ),
    ]
