# Generated by Django 5.0.6 on 2024-06-13 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0005_alter_music_views'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='music_number',
            new_name='track_count',
        ),
        migrations.RenameField(
            model_name='genre',
            old_name='about_genre',
            new_name='genre_description',
        ),
        migrations.AlterField(
            model_name='music',
            name='cover_art',
            field=models.FileField(upload_to='media/images/cover_art/'),
        ),
        migrations.AlterField(
            model_name='music',
            name='music',
            field=models.FileField(upload_to='media/music/'),
        ),
        migrations.AlterField(
            model_name='music',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='singer',
            name='birth',
            field=models.DateField(blank=True, null=True, verbose_name='Birth Date'),
        ),
        migrations.AlterField(
            model_name='singer',
            name='death',
            field=models.DateField(blank=True, null=True, verbose_name='Death Date'),
        ),
        migrations.AlterField(
            model_name='vibe',
            name='picture',
            field=models.FileField(upload_to='media/images/vibes/'),
        ),
    ]
