# Generated by Django 5.0.6 on 2024-06-15 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0006_rename_music_number_album_track_count_and_more'),
        ('Profile', '0002_alter_profile_introduction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intermediatemodel',
            name='singer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Singers', to='Music.singer'),
        ),
        migrations.AlterField(
            model_name='music',
            name='album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Music.album'),
        ),
        migrations.AlterField(
            model_name='music',
            name='music_genre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Music.genre'),
        ),
        migrations.AlterField(
            model_name='music',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Profile.profile'),
        ),
    ]
