# Generated by Django 5.0.6 on 2024-06-15 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0007_alter_intermediatemodel_singer_alter_music_album_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='genre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Music.genre'),
        ),
        migrations.AlterField(
            model_name='singer',
            name='genre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Music.genre'),
        ),
    ]
