# Generated by Django 5.0.6 on 2024-06-15 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0008_alter_album_genre_alter_singer_genre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='music',
            old_name='post_date',
            new_name='pub_date',
        ),
    ]
