# Generated by Django 5.0.6 on 2024-06-13 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='introduction',
            field=models.TextField(blank=True, null=True),
        ),
    ]
